services:
  sqlserverdb:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345@
      - MSSQL_PID=Developer
    volumes: 
      - mssqlvolume:/var/opt/mssql
      
volumes: 
    mssqlvolume: {}