services:    

  sqlserverdb:
    container_name: sqlserver
    networks:
      - my-network
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345@
      - MSSQL_PID=Developer
    volumes: 
      - mssqlvolume:/var/opt/mssql
      
  webapi:
    networks:
        - "my-network"
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:80"
    depends_on:
        - sqlserverdb

networks:
  my-network:
    driver: bridge

volumes: 
    mssqlvolume: {}